sync_address = "http://192.168.42.11:8123"
auto_sync = true
update_check = true
sync_frequency = "1h"
filter_mode = "host"
workspaces = true
filter_mode_shell_up_key_binding = "directory"
style = "compact"
inline_height = 13
exit_mode = "return-query"
enter_accept = false

[sync]
records = true

[dotfiles]
enabled = true
