return {
    override_enabled = true,
    preset = "DST_CAVE", 			        -- "SURVIVAL_TOGETHER", "MOD_MISSING", "SURVIVAL_TOGETHER_CLASSIC", "SURVIVAL_DEFAULT_PLUS", "COMPLETE_DARKNESS", "DST_CAVE", "DST_CAVE_PLUS"
    overrides = {
	-- MISC
	task_set = "cave_default", 		-- "classic", "default", "cave_default"
	start_location = "default", 			-- "caves", "default", "plus", "darkness"
	world_size = "huge", 			-- "small", "medium", "default", "huge"
	branching = "default", 			-- "never", "least", "default", "most"
	loop = "default", 			-- "never", "default", "always"
	autumn = "default", 			-- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
	winter = "default", 			-- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
	spring = "default", 			-- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
	summer = "default", 			-- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
	season_start = "default", 			-- "default", "winter", "spring", "summer", "autumnorspring", "winterorsummer", "random"
	day = "default", 			-- "default", "longday", "longdusk", "longnight", "noday", "nodusk", "nonight", "onlyday", "onlydusk", "onlynight"
	weather = "default", 			-- "never", "rare", "default", "often", "always"
	earthquakes = "rare", 			-- "never", "rare", "default", "often", "always"
	lightning = "default", 		        -- "never", "rare", "default", "often", "always"
	frograin = "default", 		        -- "never", "rare", "default", "often", "always"
	wildfires = "default", 			-- "never", "rare", "default", "often", "always"
	touchstone = "default", 			-- "never", "rare", "default", "often", "always"
	regrowth = "fast", 			-- "veryslow", "slow", "default", "fast", "veryfast"
	cavelight = "often", 			-- "veryslow", "slow", "default", "fast", "veryfast"
	boons = "often", 			-- "never", "rare", "default", "often", "always"
	prefabswaps_start = "default", 		        -- "classic", "default", "highly random"
	prefabswaps = "default", 		        -- "none", "few", "default", "many", "max"

	-- RESOURCES
	flowers = "often", 			-- "never", "rare", "default", "often", "always"
	grass = "often", 			-- "never", "rare", "default", "often", "always"
	sapling = "often", 			-- "never", "rare", "default", "often", "always"
	marshbush = "often", 			-- "never", "rare", "default", "often", "always"
	tumbleweed = "default", 			-- "never", "rare", "default", "often", "always"
	reeds = "often", 			-- "never", "rare", "default", "often", "always"
	trees = "often", 			-- "never", "rare", "default", "often", "always"
	flint = "often", 			-- "never", "rare", "default", "often", "always"
	rock = "often", 			-- "never", "rare", "default", "often", "always"
	rock_ice = "often", 			-- "never", "rare", "default", "often", "always"
	meteorspawner = "default", 			-- "never", "rare", "default", "often", "always"
	meteorshowers = "default", 			-- "never", "rare", "default", "often", "always"
	mushtree = "often", 			-- "never", "rare", "default", "often", "always"
	fern = "often", 			-- "never", "rare", "default", "often", "always"
	flower_cave = "often", 			-- "never", "rare", "default", "often", "always"
	wormlights = "often", 			-- "never", "rare", "default", "often", "always"

	-- UNPREPARED
	berrybush = "often", 			-- "never", "rare", "default", "often", "always"
	carrot = "often", 			-- "never", "rare", "default", "often", "always"
	mushroom = "often", 			-- "never", "rare", "default", "often", "always"
	cactus = "often", 			-- "never", "rare", "default", "often", "always"
	banana = "often", 			-- "never", "rare", "default", "often", "always"
	lichen = "often", 			-- "never", "rare", "default", "often", "always"

	-- ANIMALS
	rabbits = "often", 			-- "never", "rare", "default", "often", "always"
	moles = "default", 			-- "never", "rare", "default", "often", "always"
	butterfly = "often", 			-- "never", "rare", "default", "often", "always"
	birds = "default", 			-- "never", "rare", "default", "often", "always"
	buzzard = "often", 			-- "never", "rare", "default", "often", "always"
	catcoon = "often", 			-- "never", "rare", "default", "often", "always"
	perd = "often", 			-- "never", "rare", "default", "often", "always"
	pigs = "often", 			-- "never", "rare", "default", "often", "always"
	lightninggoat = "often", 			-- "never", "rare", "default", "often", "always"
	beefalo = "often", 			-- "never", "rare", "default", "often", "always"
	beefaloheat = "rare", 			-- "never", "rare", "default", "often", "always"
	hunt = "default", 			-- "never", "rare", "default", "often", "always"
	alternatehunt = "default", 			-- "never", "rare", "default", "often", "always"
	penguins = "default", 		        -- "never", "rare", "default", "often", "always"
	cave_ponds = "often", 			-- "never", "rare", "default", "often", "always"
	ponds = "default", 			-- "never", "rare", "default", "often", "always"
	bees = "default", 			-- "never", "rare", "default", "often", "always"
	angrybees = "default", 		        -- "never", "rare", "default", "often", "always"
	tallbirds = "often", 		        -- "never", "rare", "default", "often", "always"
	slurper = "often", 			-- "never", "rare", "default", "often", "always"
	bunnymen = "often", 			-- "never", "rare", "default", "often", "always"
	slurtles = "often", 			-- "never", "rare", "default", "often", "always"
	rocky = "often", 			-- "never", "rare", "default", "often", "always"
	monkey = "often", 			-- "never", "rare", "default", "often", "always"

	-- MONSTERS
	spiders = "default", 			-- "never", "rare", "default", "often", "always"
	cave_spiders = "often", 			-- "never", "rare", "default", "often", "always"
	hounds = "default", 			-- "never", "rare", "default", "often", "always"
	houndmound = "default", 			-- "never", "rare", "default", "often", "always"
	merm = "default", 			-- "never", "rare", "default", "often", "always"
	tentacles = "default", 			-- "never", "rare", "default", "often", "always"
	chess = "often", 			-- "never", "rare", "default", "often", "always"
	lureplants = "default", 			-- "never", "rare", "default", "often", "always"
	walrus = "default", 			-- "never", "rare", "default", "often", "always"
	liefs = "often", 			-- "never", "rare", "default", "often", "always"
	deciduousmonster = "odten", 			-- "never", "rare", "default", "often", "always"
	krampus = "often", 			-- "never", "rare", "default", "often", "always"
	bearger = "default", 			-- "never", "rare", "default", "often", "always"
	deerclops = "default", 		        -- "never", "rare", "default", "often", "always"
	goosemoose = "default", 			-- "never", "rare", "default", "often", "always"
	dragonfly = "default", 		        -- "never", "rare", "default", "often", "always"
	bats = "default", 			-- "never", "rare", "default", "often", "always"
	fissure = "default", 			-- "never", "rare", "default", "often", "always"
	worms = "often", 			-- "never", "rare", "default", "often", "always"
    },
